// Copyright 2023 Kuleva Anna
#ifndef MODULES_TASK_2_KULEVA_A_RADIX_DOUBLE_BATCHER_OMP_RADIX_DOUBLE_BATCHER_OMP_H_
#define MODULES_TASK_2_KULEVA_A_RADIX_DOUBLE_BATCHER_OMP_RADIX_DOUBLE_BATCHER_OMP_H_

#include <vector>

std::vector<double> radixBatcherSort(const std::vector<double>& base);

#endif  // MODULES_TASK_2_KULEVA_A_RADIX_DOUBLE_BATCHER_OMP_RADIX_DOUBLE_BATCHER_OMP_H_
